spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/sun?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: system
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate


